data_dir: "data"
inputs:
  customer_test: "data/01_raw/customer_test.csv"
  nace_codes: "data/nace_codes.csv"
plis_training_csv: "data/01_raw/plis_training.csv"
customer_meta_csv: "data/02_meta/customer.csv"
output_dir: "outputs"
submission_csv: "outputs/submission.csv"

training_validation_split:
  cutoff_date: "2025-07-01"
  test_fraction: 0.5
  random_seed: 42
  plis_training: "data/03_training_validation/plis_training.csv"
  plis_testing: "data/03_training_validation/plis_testing.csv"

scoring_parameters:
  savings_rate: 0.10
  fixed_fee_eur: 10.00
  scoring_months: 1
